INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('skin_1', 'Groene Skin', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('skin_2', 'Goude Skin', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('skin_3', 'Roze Skin', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('skin_4', 'Bruine Skin', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('skin_5', 'Blauw Skin', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('skin_6', 'Orangje Skin', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('skin_7', 'Platinum Skin', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('skin_mk2_1', 'Classic Gray', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('skin_mk2_2', 'Classic Two-Tone', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('skin_mk2_3', 'Classic White', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('skin_mk2_4', 'Classic Beige', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('skin_mk2_5', 'Classic Green', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('skin_mk2_6', 'Classic Blue', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('skin_mk2_7', 'Classic Earth', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('skin_mk2_8', 'Classic Brown & Black', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('skin_mk2_9', 'Red Contrast', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('skin_mk2_10', 'Blue Contrast', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('skin_mk2_11', 'Yellow Contrast', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('skin_mk2_12', 'Orange Contrast', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('skin_mk2_13', 'Bold Pink', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('skin_mk2_14', 'Bold Purple & Yellow', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('skin_mk2_15', 'Bold Orange', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('skin_mk2_16', 'Bold Green & Purple', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('skin_mk2_17', 'Bold Red Features', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('skin_mk2_18', 'Bold Green Features', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('skin_mk2_19', 'Bold Cyan Features', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('skin_mk2_20', 'Bold Yellow Features', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('skin_mk2_21', 'Bold Red & White', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('skin_mk2_22', 'Bold Blue & White', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('skin_mk2_23', 'Metallic Gold', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('skin_mk2_24', 'Metallic Platinum', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('skin_mk2_25', 'Metallic Gray & Lilac', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('skin_mk2_26', 'Metallic Purple & Lime', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('skin_mk2_27', 'Metallic Red', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('skin_mk2_28', 'Metallic Green', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('skin_mk2_29', 'Metallic Blue', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('skin_mk2_30', 'Metallic White & Aqua', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('skin_mk2_31', 'Metallic Red & Yellow', 1, 0, 1);


-- shops sql only -- 

INSERT INTO `shops` (`id`, `store`, `item`, `price`) VALUES (164, 'Wapentintshop', 'skin_mk2_1', 10000);
INSERT INTO `shops` (`id`, `store`, `item`, `price`) VALUES (165, 'Wapentintshop', 'skin_mk2_2', 10000);
INSERT INTO `shops` (`id`, `store`, `item`, `price`) VALUES (166, 'Wapentintshop', 'skin_mk2_3', 10000);
INSERT INTO `shops` (`id`, `store`, `item`, `price`) VALUES (167, 'Wapentintshop', 'skin_mk2_4', 10000);
INSERT INTO `shops` (`id`, `store`, `item`, `price`) VALUES (168, 'Wapentintshop', 'skin_mk2_5', 10000);
INSERT INTO `shops` (`id`, `store`, `item`, `price`) VALUES (169, 'Wapentintshop', 'skin_mk2_6', 10000);
INSERT INTO `shops` (`id`, `store`, `item`, `price`) VALUES (170, 'Wapentintshop', 'skin_mk2_7', 10000);
INSERT INTO `shops` (`id`, `store`, `item`, `price`) VALUES (171, 'Wapentintshop', 'skin_mk2_8', 10000);
INSERT INTO `shops` (`id`, `store`, `item`, `price`) VALUES (172, 'Wapentintshop', 'skin_mk2_9', 10000);
INSERT INTO `shops` (`id`, `store`, `item`, `price`) VALUES (173, 'Wapentintshop', 'skin_mk2_10', 10000);
INSERT INTO `shops` (`id`, `store`, `item`, `price`) VALUES (174, 'Wapentintshop', 'skin_mk2_11', 10000);
INSERT INTO `shops` (`id`, `store`, `item`, `price`) VALUES (175, 'Wapentintshop', 'skin_mk2_12', 10000);
INSERT INTO `shops` (`id`, `store`, `item`, `price`) VALUES (176, 'Wapentintshop', 'skin_mk2_13', 10000);
INSERT INTO `shops` (`id`, `store`, `item`, `price`) VALUES (177, 'Wapentintshop', 'skin_mk2_14', 10000);
INSERT INTO `shops` (`id`, `store`, `item`, `price`) VALUES (178, 'Wapentintshop', 'skin_mk2_15', 10000);
INSERT INTO `shops` (`id`, `store`, `item`, `price`) VALUES (179, 'Wapentintshop', 'skin_mk2_16', 10000);
INSERT INTO `shops` (`id`, `store`, `item`, `price`) VALUES (180, 'Wapentintshop', 'skin_mk2_17', 10000);
INSERT INTO `shops` (`id`, `store`, `item`, `price`) VALUES (181, 'Wapentintshop', 'skin_mk2_18', 10000);
INSERT INTO `shops` (`id`, `store`, `item`, `price`) VALUES (182, 'Wapentintshop', 'skin_mk2_19', 10000);
INSERT INTO `shops` (`id`, `store`, `item`, `price`) VALUES (183, 'Wapentintshop', 'skin_mk2_20', 10000);
INSERT INTO `shops` (`id`, `store`, `item`, `price`) VALUES (184, 'Wapentintshop', 'skin_mk2_21', 10000);
INSERT INTO `shops` (`id`, `store`, `item`, `price`) VALUES (185, 'Wapentintshop', 'skin_mk2_22', 10000);
INSERT INTO `shops` (`id`, `store`, `item`, `price`) VALUES (186, 'Wapentintshop', 'skin_mk2_23', 10000);
INSERT INTO `shops` (`id`, `store`, `item`, `price`) VALUES (187, 'Wapentintshop', 'skin_mk2_24', 10000);
INSERT INTO `shops` (`id`, `store`, `item`, `price`) VALUES (188, 'Wapentintshop', 'skin_mk2_25', 10000);
INSERT INTO `shops` (`id`, `store`, `item`, `price`) VALUES (189, 'Wapentintshop', 'skin_mk2_26', 10000);
INSERT INTO `shops` (`id`, `store`, `item`, `price`) VALUES (190, 'Wapentintshop', 'skin_mk2_27', 10000);
INSERT INTO `shops` (`id`, `store`, `item`, `price`) VALUES (191, 'Wapentintshop', 'skin_mk2_28', 10000);
INSERT INTO `shops` (`id`, `store`, `item`, `price`) VALUES (192, 'Wapentintshop', 'skin_mk2_29', 10000);
INSERT INTO `shops` (`id`, `store`, `item`, `price`) VALUES (193, 'Wapentintshop', 'skin_mk2_30', 10000);
INSERT INTO `shops` (`id`, `store`, `item`, `price`) VALUES (194, 'Wapentintshop', 'skin_mk2_31', 10000);
